/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ContentSection: typeof import('./components/ContentSection.vue')['default']
    CustomContent: typeof import('./components/CustomContent.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IEpArrowDown: typeof import('~icons/ep/arrow-down')['default']
    IEpDelete: typeof import('~icons/ep/delete')['default']
    IEpEdit: typeof import('~icons/ep/edit')['default']
    IEpPlus: typeof import('~icons/ep/plus')['default']
    NormalContent: typeof import('./components/NormalContent.vue')['default']
    OnlyDescSectionEditor: typeof import('./components/OnlyDescSectionEditor.vue')['default']
    ResumeStandard: typeof import('./components/ResumeStandard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionEditor: typeof import('./components/SectionEditor.vue')['default']
    Svgicon: typeof import('./components/svgicon/index.vue')['default']
    TagSectionEditor: typeof import('./components/TagSectionEditor.vue')['default']
  }
}
